
version: "1.0"

services:
  postgresql_db:
    image: postgres:15.1
    restart: always
    volumes:
      - ~/Volumes/postgresql:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - postgres.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "fastapi"]
      interval: 2s
      timeout: 5s
      retries: 3

  backend:
    build: ./
    restart: always
    volumes:
      - ~/volume/ordersystem:/usr/ordersystem
    ports:
      - "8000:8000"
    depends_on:
      postgresql_db:
        condition: service_healthy

networks:
  default:
    name: order_network