
version: "1.0"

services:
  postgresql_db:
    image: postgres:15.1
    restart: always
    expose:
      - 5432
    env_file:
      - postgres.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 2s
      timeout: 5s
      retries: 3

  backend:
    build: ./
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      postgresql_db:
        condition: service_healthy

networks:
  default:
    name: fastapi_network